plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Reasoning Machine
description: Machine - device, having a unique purpose, that augments or replaces human or animal effort for the accomplishment of tasks.
